"""add tipo produto_id servico_id to Pedido

Revision ID: 2fbb8bf48299
Revises: bceb1041dcb5
Create Date: 2025-11-15 18:52:29.534305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbb8bf48299'
down_revision = 'bceb1041dcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servico_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pedido_produto_id', 'produto', ['produto_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_servico_id', 'servico', ['servico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_servico_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_produto_id', type_='foreignkey')
        batch_op.drop_column('servico_id')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
