"""add is_admin to Cliente

Revision ID: bceb1041dcb5
Revises: 
Create Date: 2025-11-15 18:39:39.330444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceb1041dcb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servico_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pedido_produto_id', 'produto', ['produto_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_servico_id', 'servico', ['servico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_servico_id', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_produto_id', type_='foreignkey')
        batch_op.drop_column('servico_id')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
